version: '3.5'
services:
  php:
    container_name: rss_feed_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './api/:/usr/src/app'

  nginx:
    container_name: rss_feed_nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './api/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8080:80'
    depends_on:
      - php

  yarn:
    container_name: rss_feed_node
    image: node:12
    working_dir: /www/front
    command: "yarn start"
    ports:
      - 3001:3000
    volumes:
      - ./front:/www/front
    environment:
      API_URL: ${API_URL:-http://127.0.0.1:9000/api}

  db:
    image: mysql
    container_name: rss_feed_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_very_hard_password
      MYSQL_USER: rss
      MYSQL_PASSWORD: feed
      MYSQL_DATABASE: rss_feed
    ports:
      - "4000:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  init:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: "sh /init/docker/init.sh"
    volumes:
      - './:/init'
      - './api/:/usr/src/app'
    depends_on:
      - db
      - php
      - nginx