version: '3.5'
services:
  php:
    container_name: rss_feed_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './api/:/usr/src/app'

  nginx:
    container_name: rss_feed_nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './api/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8080:80'
    depends_on:
      - php