# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    rss.feed.url: https://www.theregister.co.uk/software/headlines.atom
    excluded.words: ['the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'I', 'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me']

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    FeedIo\Adapter\ClientInterface:
        alias: FeedIo\Adapter\Guzzle\Client

    FeedIo\Adapter\Guzzle\Client:
        autowire: true
        autoconfigure: true

    GuzzleHttp\ClientInterface:
        alias: GuzzleHttp\Client

    GuzzleHttp\Client:
        autowire: true
        autoconfigure: true

    FeedIo\FeedIo:
        autowire: true
        autoconfigure: true

    App\Service\FrequentWords\FrequentWordsCalculator:
        arguments:
            - '%excluded.words%'

    App\Service\FrequentWords\FrequentWordsService:
        alias: App\Service\FrequentWords\FrequentWordsServiceImpl